services:

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    command: centrifugo -c config.json
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    ports:
      - "8008:8000"
    networks:
      - internal-network

  api:
    build:
      context: .   
    container_name: chat_api
    ports:
      - "5000:5000"
    networks:
      - internal-network
    depends_on:
      - centrifugo
networks:
  internal-network:
    name: chat-network
    driver: bridge